ArrowsPlaceFire: true
ArrowsPlaceFireChance: 0.5
VolatileBlocks:
  #Mask values:
  # - 1:  Block catches fire / begins to burn
  # - 2:  Block burnt by fire
  # - 4:  Block got caught in a explosion (that was caused by null or a block), or when a tnt is primed and the block is a tnt
  # - 8:  Block got hit by a projectile
  # - 16: Block got hit by a burning projectile
  # - 32: Block got caught in a explosion caused by an entity
  # - 64: Block got caught in a explosion caused by another volatile reaction
  #Standard flyblock volatiles, triggers when blocks are burnt
  - ==: VolatileBlock
    Block: "#movecraft_volatiles_tte:volatiles/flyblocks"
    ExplosionPower: 1.5
    ExplosionProbability: 0.33
    IsIncendiary: true
    IsCraftPresenceNecessary: false
    EventMask: 3
  #Flyblocks when hit by projectiles
  - ==: VolatileBlock
    Block: "#movecraft_volatiles_tte:volatiles/flyblocks"
    ExplosionPower: 3.0
    ExplosionProbability: 0.33
    IsIncendiary: true
    IsCraftPresenceNecessary: false
    EventMask: 16
  #Ammunition blocks detonate on explosion, ignition and burning projectile hits
  - ==: VolatileBlock
    Block: "#movecraft_volatiles_tte:volatiles/munitions"
    ExplosionPower: 16.0
    ExplosionProbability: 0.8
    IsIncendiary: true
    IsCraftPresenceNecessary: false
    EventMask: 54
  - ==: VolatileBlock
    Block: "#movecraft_volatiles_tte:volatiles/tnt"
    ExplosionPower: 16.0
    ExplosionProbability: 0.8
    IsIncendiary: false
    IsCraftPresenceNecessary: false
    EventMask: 54